# Acknowledgments {-}

The words in this pages, the thoughts they try to convey, are the result of
years of thinking, discussing, studying, learning. My voice weaves them together,
but it draws from so many sources that have encouraged my growth, stood by me,
fed my curiosity, passion and enthusiasm for everything that makes up this text.

For their support and their ideas, I want to thank my supervisors Dirk Geeraerts,
Dirk Speelman and Benedikt Szmrecsanyi. Each of them gave their own piece, building
my confidence, encouraging me to keep exploring and learning. My main supervisor,
Dirk Geeraerts, deserves a special acknowledgment for all the hours in deep
discussion on the complex issue that is *meaning*, and what all this is about after
all. I appreciate his patience and his engagement. Every time we talked I left
feeling more excited and passionate about the topic, more confident and happy.
Hartelijk bedankt.

<!-- NOTE Where should I include the jury? -->

I must also thank my colleagues from the Linguistics Department at KU Leuven,
which at the different stages of my years here have been a lovely company and
support system. In particular, I would like to thank the members of the
Nephological Semantics project, with whom I shared so much of the excitement and
frustrations of our common project.
<!-- TODO Specify names? -->

When I joined the project, I already brought with me my own history and connection
to (cognitive) linguistics, corpora, statistics and programming. I honestly wouldn't
be where I am today if it weren't for my parents, Miguel and Patricia. They have
always supported and fostered my study and my interests, given me the tools to
grow, to face new challenges. I know I can, because they believe it too.

<!-- TODO Add Alex, Paula, mis hermanos. UNC? -->

<!-- TODO Taihou <3 -->
