# (PART) The language of clouds {-}

# The nature of clouds

<!-- Clouds don't necessarily show senses -->
<!-- :    but usage patterns --the senses are well distinguished -->
<!-- insofar they match those usage patterns. But we could have one usage pattern for multiple -->
<!-- senses, multiple usage patterns for one sense, and, more importantly, different degrees -->
<!-- of definition of each usage pattern. -->

<!-- It is not a matter of frequency -->
<!-- :    we can have infrequent senses/patterns that are nonetheless strong enough to form -->
<!-- a clear group; and -->
<!-- :    extremely frequent senses can also be grouped separately, they don't necessarily -->
<!-- absorb the minor senses/patterns, if their pattern is characteristic enough. -->

When we talk about language, we often talk about the linguistic sign. That term itself
is most often linked to Saussure
<!-- TODO add citation? -->
and structuralism, but it is not far from the form-meaning pairing in cognitive linguistics.
<!-- TODO add references, maybe some definition? -->

The different branches and theoretical frameworks in linguistic differ by how they
define each of the elements of the pair. For example, referring to "meaning" or *signifié*
aspect: is it linguistic internal? Does it include reference? Does it include *social meaning*?
Moreover: should this relationship be studied in relation to an organized system,
or discovered from the turbulent chaos of language use?

Cognitive linguistics, the theoretical framework that has guided these studies, accepts
a broadly encompassing notion of *meaning* ---which certainly does not make it easy to
define it--- and values the study of language in use. This is wonderfully compatible with
the Distributional Hypothesis, the methodological framework that inspires this research,
but can lead to disappointing misunderstandings.

The Distributional Hypothesis basically states a correlation between difference in
distributional behavior (difference in how forms are used) and semantic difference.

<!-- TODO add nice citation -->

A popular interpretation of this Hypothesis involves using distributional patterns,
such as word vectors, as *operationalizations of meaning*. The word space becomes a
semantic space, and a type-level model such as Latent Semantic Analysis (LSA)
"constructs a single vector for a word meaning" [@bolognesi_2020 82]. This is the core
argument of these models, the selling point of distributional models and word embeddings.

However, as the analysis in this research project can make clear, *usage is not meaning*.
<!-- TODO Maybe find a citation from McEnery? -->
Form can be simplified, but both usage and meaning are extremely complex phenomena,
and the simplification or abstraction we may make of one will not necessarily correlate
with the simplification or abstraction we prefer for the other. Usage correlates with
meaning, but that doesn't mean that any specific distributional model will correspond
to dictionary senses and the case is, unfortunately, that it doesn't.

Even @sahlgren_2006 makes a point of treating semantic similarity in very vague terms,
only distinguishing between paradigmatic and syntagmatic relationships.

A more useful idea might be to think of a triad of form, meaning, and usage. This
does not necessarily complexify the picture, since *usage*, in its variety, is very
concrete and operationalizable. Even if we cannot equate usage patterns to meaning,
the relationship between form and usage patterns can still inform our understanding of
meaning. It certainly does not render distributional methods useless. We just have
to be careful not to conflate correlated but different phenomena, just like we should
not conflate form and meaning.


