# HDBSCAN

The visual exploration is extremely useful for a thorough, qualitative description
of the vector space models. However, such an application can also become an obstacle
to a truly systematic, scientific description. I would avoid talking about objectivity:
neither of us, individually, can truly be objective, and we should instead strive for a
humble admission of our own partiality and a fruitful combination of all our partialities.

When describing a cloud ---in particular these clouds that refuse to show clear images,
perfect sense disambiguation, distinct clusters---, how can we ensure that what we
see will be found by other researchers? How can we make our observations, if not
inherently valid, at least reproducible?
This is, after all, the goal we strive for when we embark on quantitative methods.

One tool that can help us systematize our observations, such as the tightness or at least
existEnce of distinct islands on a plot, is
Hierarchical Density-Based Spatial Clustering of Applications (HDBSCAN) [@campello.etal_2013].
This algorithm basically tries to distinguish dense areas separated by less dense areas[^hdbscan]
and allows for noisy data. In other words, unlike traditional hierarchical clustering,
it will not try to cluster all of the points in the dataset, but instead may discard those
that are too far from everything else. Moreover, in comparison to its non hierarchical counterpart,
DBSCAN,
<!-- TODO add citation -->
it requires only one parameter to be set *a priori*, namely $minPts$.

[^hdbscan]: For a friendly description of how the algorithm works, the reader is directed to @mcinnes.etal_2016; for an even friendlier explanation, find the authors on YouTube.

The $minPts$ parameter indicates the minimum size of a dense group of points to be considered
a cluster. An isolated dense group of points for which $n < minPts$ will be considered noise.
In the case studies described here we have fixed $minPts$ to 8, which seems a reasonable
size for the smallest clusters, but it would be interested to look more systematically into
the effect of lowering this threshold. Rising the threshold, on the other hand, would
increase the proportion of points that are considered noise, which is already very high.

Like other clustering algorithms and the dimensionality reduction techniques,
HDBSCAN can take a token-context matrix as input or a distance matrix. We have used
the transformed distance matrix, that is, the same input fed into the t-SNE algorithm,
for the `hdbscan()` function of the {dbscan} R package [@R-dbscan]. The output includes,
among other things, the cluster assignment, with noise points assigned to a cluster 0,
and epsilon values, which can be used as an estimate of density.

HDBSCAN estimates the density of [the area in which we find] a point $a$ by calculating its
core distance $core_{k}(a)$, which is the distance to its $k$ nearest neighbor, $k$ being $minPts - 1$.
Then it recalculates the distance matrix by defining a new distance measure, called
*mutual reachability*, which is defined as the maximum between the distance between
the items $d(a, b)$ and each of their core distances.

$$d_{mreach-k}(a,b) = max(core_{k}(a), core_{k}(b), d(a,b))$$

<!-- TODO Check if that stands like that in the paper and cite appropriate page number -->

Once the algorithm obtains these distances, it uses a single linkage method to create
hierarchical clusters, then using again $minPts$ and other calculations to merge them
into the final selection. The `eps` (epsilon) values returned by `hdbscan()` indicate
the height, in the single linkeage tree, at which each point was joined to a cluster,
and can thus be used as a proxy for its "density".

This is intuitively more clear if we map the clustering solution to colors and the
`eps` value to transparency in a t-SNE plot with perplexity 30. For the most part,
the results converge, which has two main upsides. In the first place, we have independent
confirmation of the structure found by t-SNE, as a different algorithm processing
the same input returns compatible output. Second, insofar the HDBSCAN output matches
our visual assessment, it can systematize it and render it reproducible.

This wonders notwithstanding, the compatibility between the HDBSCAN output and visual examination is not guaranteed. We might find interesting tokens that are discarded as noise, or structure within
a single HDBSCAN cluster. However, it must be noted that this match (or lack thereof)
has been assessed only between `dbscan::hdbscan()` with $minPts = 8$ and
`Rtsne::Rtsne()` with $perplexity = 30$. It would be an interesting avenue for further research to experiment with other combinations, and of course UMAP output.

